name: Test Theme

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Test Build Example Site
        run: |
          cd exampleSite
          THEME_NAME=$(basename $GITHUB_WORKSPACE)
          hugo --themesDir ../.. --theme $THEME_NAME --minify
